config/routes.rb
Rails.application.routes.draw do
  get 'postulations/new'
  get 'postulations/create'
  resources :job_postings
  get 'pages/index'
  get 'job_postings/index'
  #devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "job_postings#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',  
    registrations: 'users/registrations',  
    
  }
  
  # Defino las rutas para que los usuarios que no sean admin, puedan postular a empleos
  resources :job_postings do
    resources :postulations, only: [:new, :create]
  end
end

app/models/job_posting.rb
class JobPosting < ApplicationRecord
  belongs_to :user
  has_many :postulations, dependent: :destroy
  has_many :applicants, through: :postulations, source: :user
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  before_action :set_job_posting, only: %i[ show edit update destroy ]
  #before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /job_postings or /job_postings.json
  def index
    @job_postings = JobPosting.all
  end

  # GET /job_postings/1 or /job_postings/1.json
  def show
    if user_signed_in?
      # Si el usuario está autenticado, puede ver el trabajo.
    else
      # El usuario si no está autenticado, se redirige a la página de inicio de sesión.
      redirect_to new_user_session_path, alert: "You need to sign in to view this job posting."
    end
    @job_posting = JobPosting.find(params[:id])
    @postulations = @job_posting.postulations
  end

  # GET /job_postings/new
  def new
    if current_user.admin?
      @job_posting = JobPosting.new
    else
      redirect_to job_postings_path, alert: "Only administrators can create job postings."
    end
  end

  # GET /job_postings/1/edit
  def edit
    authorize_edit
  end

  # POST /job_postings or /job_postings.json
  def create
    @job_posting = current_user.job_postings.build(job_posting_params)

    respond_to do |format|
      if @job_posting.save
        format.html { redirect_to job_posting_url(@job_posting), notice: "Job posting was successfully created." }
        format.json { render :show, status: :created, location: @job_posting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end




  
  # PATCH/PUT /job_postings/1 or /job_postings/1.json
  def update
    authorize_edit
    respond_to do |format|
      if @job_posting.update(job_posting_params)
        format.html { redirect_to job_posting_url(@job_posting), notice: "Job posting was successfully updated." }
        format.json { render :show, status: :ok, location: @job_posting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_postings/1 or /job_postings/1.json
  def destroy
    authorize_edit
    @job_posting.destroy

    respond_to do |format|
      format.html { redirect_to job_postings_url, notice: "Job posting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job_posting = JobPosting.find(params[:id])
    end
    
    def set_job_posting
      @job_posting = JobPosting.find(params[:id])
    end

    def authorize_edit
      unless current_user.admin?
        redirect_to jobs_path, alert: 'You do not have permission to perform this action.'
      end
    end
    
    # Only allow a list of trusted parameters through.
    def job_posting_params
      params.require(:job_posting).permit(:title, :department, :description)
    end
end

app/helpers/job_postings_helper.rb
module JobPostingsHelper
end

app/views/job_postings/_form.html.erb
<%= form_with(model: job_posting) do |form| %>
  <% if job_posting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job_posting.errors.count, "error") %> prohibited this job_posting from being saved:</h2>

      <ul>
        <% job_posting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :department, style: "display: block" %>
    <%= form.text_field :department %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
<!--
  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>
-->

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/job_postings/_job_posting.html.erb
<div id="<%= dom_id job_posting %>">
  <p>
    <strong>Title:</strong>
    <%= job_posting.title %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= job_posting.department %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= job_posting.description %>
  </p>

  <p>
    <strong>Creado por:</strong>
    <%= job_posting.user.name %>
  </p>

</div>

app/views/job_postings/edit.html.erb
<div class="container">
  <h1>Editing job posting</h1>

  <%= render "form", job_posting: @job_posting %>

  <br>

  <div>
    <%= link_to "Show this job posting", @job_posting %> |
    <%= link_to "Back to job postings", job_postings_path %>
  </div>

</div>

app/views/job_postings/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <h1>Job postings</h1>

  <div id="job_postings">
    <% @job_postings.each do |job_posting| %>
      <%= render job_posting %>
      <p>
        <%= link_to "Show this job posting", job_posting %>
      </p>
      <hr>
    <% end %>
  </div>

 <!--
    <% if current_user %>
      <%= link_to "New job posting", new_job_posting_path %>
    <% end %>
 -->  
</div>

app/views/job_postings/new.html.erb
<div class="container">
  <h1>New job posting</h1>
  <% unless current_user.admin? %>
    <p class="alert-red">You do not have permission to create job postings.</p>
  <% end %>

  <%= render "form", job_posting: @job_posting %>

  <br>

  <div>
    <%= link_to "Back to job postings", job_postings_path %>
  </div>

</div>

app/views/job_postings/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @job_posting %>
  
    <% unless current_user.admin? %>

    <% if current_user.postulations.exists?(job_posting_id: @job_posting.id) %>
    <p>You have already applied for this position!.</p>
      <% else %>
          <%= link_to "Apply for this position", new_job_posting_postulation_path(@job_posting), class: 'btn btn-primary' %>
      <% end %>
    <% end %>

  <% if user_signed_in? && current_user.admin? %>     
    <h2>Applicants:</h2>
      <ul>
        <% @job_posting.postulations.each do |postulation| %>
          <li><%= postulation.user.name %></li>
        <% end %>
      </ul>    
    <div>
      <%= link_to "Edit this job posting", edit_job_posting_path(@job_posting) %> |
      <%= link_to "Back to job postings", job_postings_path %>
      <%= button_to "Destroy this job posting", @job_posting, method: :delete %>
    </div>
  <% else %>
      <%= link_to "Back to job postings", job_postings_path %>
  <% end %>

</div>